packages:
  - api
  - web-client
  - packages/*

allowBuilds:
  '@swc/core': true
  better-sqlite3: true
  core-js: true
  esbuild: true
  node-gyp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - nvp.ui@0.9.2

peerDependencyRules:
  allowAny:
    - prettier
    - '@ember-data/*'
