/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountInvitationSchema extends BaseModel {
  static $columns = ['acceptedAt', 'acceptedBy', 'accountId', 'createdAt', 'expiresAt', 'id', 'invitedBy', 'role', 'token'] as const
  $columns = AccountInvitationSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column()
  declare acceptedBy: string | null
  @column()
  declare accountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invitedBy: string
  @column()
  declare role: string
  @column()
  declare token: string
}

export class AccountMembershipSchema extends BaseModel {
  static $columns = ['accountId', 'createdAt', 'id', 'role', 'userId'] as const
  $columns = AccountMembershipSchema.$columns
  @column()
  declare accountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare role: string
  @column()
  declare userId: string
}

export class AccountSchema extends BaseModel {
  static $columns = ['adminId', 'createdAt', 'id', 'isFree', 'isPersonal', 'name', 'stripeCancelAtPeriodEnd', 'stripeCurrentPeriodEnd', 'stripeCurrentPeriodStart', 'stripeCustomerId', 'stripeLastSyncedAt', 'stripePaymentMethodBrand', 'stripePaymentMethodLast4', 'stripePriceId', 'stripeSubscriptionId', 'stripeSubscriptionStatus', 'updatedAt'] as const
  $columns = AccountSchema.$columns
  @column()
  declare adminId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFree: boolean | null
  @column()
  declare isPersonal: boolean
  @column()
  declare name: string
  @column()
  declare stripeCancelAtPeriodEnd: boolean | null
  @column()
  declare stripeCurrentPeriodEnd: bigint | number | null
  @column()
  declare stripeCurrentPeriodStart: bigint | number | null
  @column()
  declare stripeCustomerId: string | null
  @column.dateTime()
  declare stripeLastSyncedAt: DateTime | null
  @column()
  declare stripePaymentMethodBrand: string | null
  @column()
  declare stripePaymentMethodLast4: string | null
  @column()
  declare stripePriceId: string | null
  @column()
  declare stripeSubscriptionId: string | null
  @column()
  declare stripeSubscriptionStatus: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ApiKeySchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = ApiKeySchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CustomDomainSchema extends BaseModel {
  static $columns = ['accountId', 'createdAt', 'hostname', 'id'] as const
  $columns = CustomDomainSchema.$columns
  @column()
  declare accountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare hostname: string
  @column({ isPrimary: true })
  declare id: number
}

export class CustomLinkSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'linkId', 'name', 'updatedAt'] as const
  $columns = CustomLinkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare linkId: string
  @column()
  declare name: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LinkVisitSchema extends BaseModel {
  static $columns = ['id', 'linkId', 'referrer', 'userAgent', 'visitedAt'] as const
  $columns = LinkVisitSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare linkId: string
  @column()
  declare referrer: string | null
  @column()
  declare userAgent: string | null
  @column.dateTime()
  declare visitedAt: DateTime
}

export class LinkSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'domain', 'expiresAt', 'id', 'original', 'ownedBy', 'updatedAt', 'visits'] as const
  $columns = LinkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string
  @column()
  declare domain: string | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare original: string
  @column()
  declare ownedBy: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare visits: number | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class StripeWebhookEventSchema extends BaseModel {
  static $columns = ['customerId', 'eventId', 'eventType', 'processedAt'] as const
  $columns = StripeWebhookEventSchema.$columns
  @column()
  declare customerId: string | null
  @column({ isPrimary: true })
  declare eventId: string
  @column()
  declare eventType: string
  @column.dateTime()
  declare processedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['accountId', 'createdAt', 'id', 'isStaff', 'name', 'oauthGithubId', 'oauthGithubToken', 'oauthGoogleId', 'oauthGoogleToken', 'oauthTwitterId', 'oauthTwitterToken', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare accountId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isStaff: boolean
  @column()
  declare name: string | null
  @column()
  declare oauthGithubId: string | null
  @column()
  declare oauthGithubToken: string | null
  @column()
  declare oauthGoogleId: string | null
  @column()
  declare oauthGoogleToken: string | null
  @column()
  declare oauthTwitterId: string | null
  @column()
  declare oauthTwitterToken: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
