name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}
  merge_group:
    types: [checks_requested]

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: "pnpm lint:fix"
      - run: git diff --exit-code

  types:
    name: Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm typecheck

  tests_api:
    name: API Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      # bug with ignore-scripts=true?
      # - run: pnpm rebuild
      - run: ./config/hosts.sh
      - run: |
          pnpm rebuild
          pnpm test
        working-directory: api

  tests_spa:
    name: SPA Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      # bug with ignore-scripts=true?
      # - run: pnpm rebuild
      - run: pnpm test
        working-directory: web-client

  build_api_image:
    name: "Build API Image"
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: [tests_api, tests_spa]
    steps:
      - uses: actions/checkout@v4
      - run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - run: heroku container:push web --app ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

